global using System.Collections.Generic;
global using System.Linq;
global using Microsoft.AspNetCore.Mvc;
global using System.Collections.Generic;
global using System.Linq;
global using Microsoft.AspNetCore.Mvc;
global using WordFinderAPI.Interfaces;
global using WordFinderAPI.Models;
global using WordFinderAPI.Constants;